version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: resume_builder_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resume_builder
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Uncomment when backend is ready to run in Docker
  # backend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: resume_builder_api
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     DATABASE_URL: postgres://postgres:postgres@postgres:5432/resume_builder?sslmode=disable
  #     OPENAI_API_KEY: ${OPENAI_API_KEY}
  #     JWT_SECRET: ${JWT_SECRET}
  #   depends_on:
  #     postgres:
  #       condition: service_healthy

volumes:
  postgres_data: